FROM python:3.12-slim

# Crear una carpeta de trabajo
WORKDIR /app

# Copia de requerimientos
COPY requirements.txt .

# Instalalos
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del proyecto
COPY ./app ./app 

# Exponer el puerto
EXPOSE 8000

# Comando para ejecutar FASTAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]