FROM python:3.12-slim

# Crear una carpeta de trabajo
WORKDIR /app

# Copia de requerimientos
COPY requeriments.txt .

# Instalalos
RUN pip install --no-cache-dir -r requeriments.txt

# Copiar el código del proyecto
COPY ./app ./app 

# Exponer el NUEVO puerto
EXPOSE 8081

# Comando para ejecutar FASTAPI en el puerto 8081
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8081"]