version: '3.8'

services:
  api:
    build: .
    container_name: mi_api_jwt_server
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8081 --reload